spring:
  application:
    name: config-service
  cloud:
    bus:
      enabled: true
      id: config-service
    stream:
      kafka:
        binder:
          brokers: kafka1:19092
    config:
      server:
        git:
          uri: https://github.com/HiddenPrj/compaj-cloud-config.git
          search-paths: config
server:
  port: 8888