spring:
  application:
    name: config-service
  cloud:
    bus:
      enabled: true
      id: config-service
    stream:
      kafka:
        binder:
          brokers: kafka1:19092
    config:
      server:
        git:
          uri: file:///app/ #https://github.com/CrissNamon/compaj-cloud.git
          search-paths: config
server:
  port: 8888